# Syntax reference: https://docs.gitlab.com/ci/yaml/

# Overview:
# Pipelines run only on merge requests, schedules, tags, or the develop branch (default).
# - A schedule pipeline (e.g. nightly build) runs all the jobs.
# - A tag pipeline runs most of the jobs but skips some (also, v#.#.# tags are special).
# - Merge requests and pushes to develop will run
#   - few jobs if only `docs/` files changed,
#   - all jobs if any other files changed.

.anchors:
  .manual-allow_failure: &manual-allow_failure
    when: manual
    allow_failure: true

# using an image that can do git, docker, docker-compose
image: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-fair/ci-runner:latest

default:
  tags:
    - cloud # Necessary to select the right CI runner

variables:
  DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
  DOCKER_HOST: tcp://docker-dind:2375
  DOCKER_TLS_CERTDIR: ""
  UV_VERSION: 0.6
  PYTHON_VERSION: 3.12

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_NAME}

stages:
  - build
  - test
  - deploy
  - release

# JOBS
update changelog:
  stage: build
  when: manual
  script:
    - curl -X POST "https://gitlab.mpcdf.mpg.de/api/v4/projects/$CI_PROJECT_ID/repository/changelog?branch=${CI_COMMIT_REF_NAME}&version=${CI_COMMIT_REF_NAME:1}&access_token=$CI_ACCESS_TOKEN&message=Add%20changelog%20for%20version%20$CI_COMMIT_REF_NAME%20%5Bskip-ci%5D"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+$/

.build_image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "."
      --dockerfile "Dockerfile"
      --target "${TARGET}"
      --destination "${DESTINATION}"
      --cache-repo "${CI_REGISTRY_IMAGE}/cache"
      --cache=true
      --skip-unused-stages
      --build-arg SETUPTOOLS_SCM_PRETEND_VERSION

build gui:
  stage: build
  extends: .build_image
  variables:
    TARGET: dev_node
    DESTINATION: "${CI_REGISTRY_IMAGE}/dev_node:${DOCKER_TAG}"

# kaniko image doesn't contain pip, so we have to save the scm_pretend_version in an earlier job and reuse it later
update_scm_pretend_version:
  stage: build
  script:
    - pip install --upgrade setuptools_scm
    - echo "SETUPTOOLS_SCM_PRETEND_VERSION=$(python -m setuptools_scm)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build python:
  stage: build
  extends: .build_image
  variables:
    TARGET: dev_python
    DESTINATION: "${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}"

python linting:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}
  script:
    - ruff check nomad tests
    - ruff format nomad tests --check
    - ruff check nomad tests --output-format gitlab > $CI_PROJECT_DIR/gl-code-quality-report.json
    - mypy nomad tests
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  artifacts:
    name: "nomad_code_quality"
    when: always
    reports:
      codequality: gl-code-quality-report.json
    expire_in: never

python package clean up:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}
  script:
    - python scripts/cleanup_packages.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG
      <<: *manual-allow_failure

check python dependencies:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-bookworm
  script:
    - scripts/check_python_dependencies.sh
  rules:
    - if: $CI_COMMIT_TAG
      when: never

.base_test:
  image: ${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}
  stage: test
  services:
    - name: rabbitmq:4
      alias: rabbitmq
    - name: elasticsearch:7.17.24
      alias: elastic
      command:
        - bash
        - "-c"
        - ES_JAVA_OPTS="-Xms512m -Xmx512m" docker-entrypoint.sh elasticsearch -Ediscovery.type=single-node -Expack.security.enabled=false
    - name: mongo:5
      alias: mongo
  variables:
    RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
    RABBITMQ_DEFAULT_USER: rabbitmq
    RABBITMQ_DEFAULT_PASS: rabbitmq
    RABBITMQ_DEFAULT_VHOST: /
    NOMAD_RABBITMQ_HOST: rabbitmq
    NOMAD_ELASTIC_HOST: elastic
    NOMAD_MONGO_HOST: mongo
    NOMAD_KEYCLOAK_PASSWORD: ${CI_KEYCLOAK_ADMIN_PASSWORD}
    NOMAD_NORMALIZE_SPRINGER_DB_PATH: /nomad/fairdi/db/data/springer.msg
  before_script:
    - scripts/check_elastic.sh
    - uv pip install -e ".[dev]"
    - uv pip install -r requirements-plugins.txt -c requirements-dev.txt # remove this after moving to distro

generate pytest timings:
  extends: .base_test
  script:
    - python -m pytest --store-durations
  artifacts:
    expire_in: 1 days
    paths:
      - .test_durations
  rules:
    - if: $CI_COMMIT_TAG
      when: never
      <<: *manual-allow_failure

python tests:
  parallel: 4
  extends: .base_test
  script:
    - python -m pytest --cov=nomad --cov-report term --cov-config=.coveragerc -sv tests --splits $CI_NODE_TOTAL --group=$CI_NODE_INDEX
  after_script:
    - cp .coverage .coverage_${CI_NODE_INDEX}
  artifacts:
    expire_in: 1 days
    paths:
      - .coverage_${CI_NODE_INDEX}
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

python coverage report:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}
  needs: ["python tests"]
  script:
    - coverage combine .coverage_*
    - coverage report
    - coverage xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

gui linting:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/dev_node:${DOCKER_TAG}
  variables:
    GIT_STRATEGY: none
  before_script:
    - cd /app/gui
  script:
    - yarn run lint
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

generate gui artifacts:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/dev_python:${DOCKER_TAG}
  script:
    - uv pip install ".[dev,parsing,infrastructure]"
    - uv pip install -r requirements-plugins.txt -c requirements-dev.txt # remove this after moving to distro
    - scripts/generate_gui_test_artifacts.sh
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  artifacts:
    paths:
      - gui/tests/env.js
      - gui/tests/artifacts.js
    expire_in: 1 days

gui tests:
  stage: test
  needs: ["generate gui artifacts"]
  image: ${CI_REGISTRY_IMAGE}/dev_node:${DOCKER_TAG}
  variables:
    GIT_STRATEGY: none
  before_script:
    - cp gui/tests/env.js /app/gui/tests/env.js
    - cp gui/tests/artifacts.js /app/gui/tests/artifacts.js
    - cd /app/gui
  script:
    - yarn test --ci --collectCoverage --reporters=default --reporters=jest-junit --silent
      --testPathIgnorePatterns=src/components/entry/ArchiveEntryView.spec.js
      --testPathIgnorePatterns=src/components/archive/FileBrowser.spec.js
      --testPathIgnorePatterns=src/components/archive/MetainfoBrowser.spec.js
  after_script:
    - cd /app/gui
    - cp junit.xml $CI_PROJECT_DIR
    - cp coverage/cobertura-coverage.xml $CI_PROJECT_DIR
  timeout: 1h 30m
  coverage: /Lines\s*:\s*(\d+.?\d*)%/
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-coverage.xml
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

build python package:
  stage: test
  variables:
    SETUPTOOLS_SCM_PRETEND_VERSION: "${SETUPTOOLS_SCM_PRETEND_VERSION}"
  extends: .build_image
  script:
    - /kaniko/executor
      --context "."
      --dockerfile "Dockerfile"
      --target "dev_package"
      --destination "${CI_REGISTRY_IMAGE}/dev_package:${DOCKER_TAG}"
      --skip-unused-stages
      --cache-repo "${CI_REGISTRY_IMAGE}/cache"
      --cache=true
      --build-arg SETUPTOOLS_SCM_PRETEND_VERSION
    - mkdir -p $CI_PROJECT_DIR/dist
    - cp -r /app/dist/* $CI_PROJECT_DIR/dist
    - cp /app/tests/data/parsers/archive.json $CI_PROJECT_DIR/
    - cp /app/tests/data/examples/example.out $CI_PROJECT_DIR/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - dist/
      - archive.json
      - example.out

python package install tests:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-bookworm
  needs: ["build python package"]
  variables:
    UV_LINK_MODE: copy
    GIT_STRATEGY: none
  script:
    - |
      for PYTHON_VERSION in 3.10 3.11 3.12; do
        echo "Running for Python $PYTHON_VERSION"

        uv venv -p $PYTHON_VERSION

        uv pip install dist/nomad_*.whl

        ./.venv/bin/python -c 'import nomad.cli'
        ./.venv/bin/python -c 'from nomad.client import ArchiveQuery'
        ./.venv/bin/python -m nomad.cli parse --skip-normalizers archive.json

        echo "\n"
      done
  rules:
    - if: $CI_COMMIT_TAG
    - when: on_success

release python package:
  stage: release
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-bookworm
  variables:
    GIT_STRATEGY: none
  script: uv publish -u gitlab-ci-token -p ${CI_JOB_TOKEN} --publish-url https://gitlab.mpcdf.mpg.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $NIGHTLY
    - if: $CI_COMMIT_TAG
      <<: *manual-allow_failure
    - <<: [*manual-allow_failure]

release pypi package:
  stage: release
  variables:
    GIT_STRATEGY: none
  before_script:
    - pip install twine
  script: twine upload -u $CI_TWINE_USER -p $CI_TWINE_PASSWORD dist/*
  rules:
    - if: $CI_COMMIT_TAG
      <<: *manual-allow_failure

push to github:
  stage: release
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push "https://${CI_GITHUB_ACCESS_TOKEN}@github.com/FAIRmat-NFDI/nomad.git" ${CI_COMMIT_REF_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_TAG
