/*
 * Copyright The NOMAD Authors.
 *
 * This file is part of NOMAD. See https://nomad-lab.eu for further info.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by NOMAD CLI. Do not edit manually.

export const unitList = [
  {
    name: 'ampere',
    dimension: 'current',
    label: 'Ampere',
    abbreviation: 'A',
    aliases: [
      'A',
      'amp'
    ]
  },
  {
    name: 'bit',
    dimension: 'information',
    label: 'Bit',
    abbreviation: 'bit',
    aliases: []
  },
  {
    name: 'candela',
    dimension: 'luminosity',
    label: 'Candela',
    abbreviation: 'cd',
    aliases: [
      'cd',
      'candle'
    ]
  },
  {
    name: 'dimensionless',
    dimension: 'dimensionless',
    label: 'Dimensionless',
    abbreviation: ''
  },
  {
    name: 'kelvin',
    dimension: 'temperature',
    label: 'Kelvin',
    abbreviation: 'K',
    aliases: [
      'K',
      'degK',
      '\u00b0K',
      'degree_Kelvin',
      'degreeK'
    ]
  },
  {
    name: 'kilogram',
    dimension: 'mass',
    label: 'Kilogram',
    abbreviation: 'kg'
  },
  {
    name: 'meter',
    dimension: 'length',
    label: 'Meter',
    abbreviation: 'm',
    aliases: [
      'm',
      'metre'
    ]
  },
  {
    name: 'mole',
    dimension: 'substance',
    label: 'Mole',
    abbreviation: 'mol',
    aliases: [
      'mol'
    ]
  },
  {
    name: 'pixel',
    dimension: 'digital_image_resolution',
    label: 'Pixel',
    abbreviation: 'px',
    aliases: [
      'px',
      'pel'
    ]
  },
  {
    name: 'radian',
    dimension: 'angle',
    label: 'Radian',
    abbreviation: 'rad',
    aliases: [
      'rad'
    ]
  },
  {
    name: 'second',
    dimension: 'time',
    label: 'Second',
    abbreviation: 's',
    aliases: [
      's',
      'sec'
    ]
  },
  {
    name: 'US_international_ampere',
    dimension: 'current',
    label: 'US international ampere',
    abbreviation: 'A_US',
    aliases: [
      'A_US'
    ],
    definition: '0.9998350816345909 ampere',
    offset: 0.0
  },
  {
    name: 'US_international_ohm',
    dimension: 'resistance',
    label: 'US international ohm',
    abbreviation: '\u03a9_US',
    aliases: [
      '\u03a9_US',
      'ohm_US'
    ],
    definition: '1.000495 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'US_international_volt',
    dimension: 'electric_potential',
    label: 'US international volt',
    abbreviation: 'V_US',
    aliases: [
      'V_US'
    ],
    definition: '1.00033 kilogram * meter ^ 2 / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'abampere',
    dimension: 'current',
    label: 'Abampere',
    abbreviation: 'abA',
    aliases: [
      'abA'
    ],
    definition: '10 ampere',
    offset: 0.0
  },
  {
    name: 'abcoulomb',
    dimension: 'charge',
    label: 'Abcoulomb',
    abbreviation: 'abC',
    aliases: [
      'abC'
    ],
    definition: '10 ampere * second',
    offset: 0.0
  },
  {
    name: 'abfarad',
    dimension: 'capacitance',
    label: 'Abfarad',
    abbreviation: 'abF',
    aliases: [
      'abF'
    ],
    definition: '1000000000.0 ampere ^ 2 * second ^ 4 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'abhenry',
    dimension: 'inductance',
    label: 'Abhenry',
    abbreviation: 'abH',
    aliases: [
      'abH'
    ],
    definition: '1.0000000000000003e-09 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'abohm',
    dimension: 'resistance',
    label: 'Abohm',
    abbreviation: 'ab\u03a9',
    aliases: [
      'ab\u03a9'
    ],
    definition: '1.0000000000000003e-09 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'absiemens',
    dimension: 'conductance',
    label: 'Absiemens',
    abbreviation: 'abS',
    aliases: [
      'abS',
      'abmho'
    ],
    definition: '1000000000.0 ampere ^ 2 * second ^ 3 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'abvolt',
    dimension: 'electric_potential',
    label: 'Abvolt',
    abbreviation: 'abV',
    aliases: [
      'abV'
    ],
    definition: '1e-08 kilogram * meter ^ 2 / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'angstrom',
    dimension: 'length',
    label: 'Angstrom',
    abbreviation: '\u00c5',
    aliases: [
      '\u00c5',
      '\u00e5ngstr\u00f6m',
      '\u212b'
    ],
    definition: '1e-10 meter',
    offset: 0.0
  },
  {
    name: 'arcminute',
    dimension: 'angle',
    label: 'Arcminute',
    abbreviation: 'arcmin',
    aliases: [
      'arcmin',
      'arc_minute',
      'angular_minute'
    ],
    definition: '0.00029088820866572163 radian',
    offset: 0.0
  },
  {
    name: 'arcsecond',
    dimension: 'angle',
    label: 'Arcsecond',
    abbreviation: 'arcsec',
    aliases: [
      'arcsec',
      'arc_second',
      'angular_second'
    ],
    definition: '4.84813681109536e-06 radian',
    offset: 0.0
  },
  {
    name: 'atomic_mass_constant',
    dimension: 'mass',
    label: 'Atomic mass constant',
    abbreviation: 'm_u',
    aliases: [
      'm_u'
    ],
    definition: '1.6605390666e-27 kilogram',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_current',
    dimension: 'current',
    label: 'Atomic unit of current',
    abbreviation: 'a_u_current',
    aliases: [
      'a_u_current'
    ],
    definition: '0.006623618237509995 ampere',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_electric_field',
    dimension: 'electric_field',
    label: 'Atomic unit of electric field',
    abbreviation: 'a_u_electric_field',
    aliases: [
      'a_u_electric_field'
    ],
    definition: '514220674762.31793 kilogram * meter / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_force',
    dimension: 'force',
    label: 'Atomic unit of force',
    abbreviation: 'a_u_force',
    aliases: [
      'a_u_force'
    ],
    definition: '8.238723498238991e-08 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_intensity',
    dimension: 'intensity',
    label: 'Atomic unit of intensity',
    abbreviation: 'a_u_intensity',
    aliases: [
      'a_u_intensity'
    ],
    definition: '3.509445520566477e+20 kilogram / second ^ 3',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_length',
    dimension: 'length',
    label: 'Atomic unit of length',
    abbreviation: 'bohr',
    aliases: [
      'bohr',
      'a_0',
      'a0',
      'bohr_radius',
      'a_u_length'
    ],
    definition: '5.2917721090397754e-11 meter',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_pressure',
    dimension: 'pressure',
    label: 'Atomic unit of pressure',
    abbreviation: 'a_u_pressure',
    aliases: [
      'a_u_pressure'
    ],
    definition: '29421015696359.54 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_temperature',
    dimension: 'temperature',
    label: 'Atomic unit of temperature',
    abbreviation: 'a_u_temp',
    aliases: [
      'a_u_temp'
    ],
    definition: '315775.0248040719 kelvin',
    offset: 0.0
  },
  {
    name: 'atomic_unit_of_time',
    dimension: 'time',
    label: 'Atomic unit of time',
    abbreviation: 'a_u_time',
    aliases: [
      'a_u_time'
    ],
    definition: '2.4188843265856806e-17 second',
    offset: 0.0
  },
  {
    name: 'bar',
    dimension: 'pressure',
    label: 'Bar',
    abbreviation: 'bar',
    aliases: [],
    definition: '100000.0 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'barn',
    dimension: 'area',
    label: 'Barn',
    abbreviation: 'b',
    aliases: [
      'b'
    ],
    definition: '1e-28 meter ^ 2',
    offset: 0.0
  },
  {
    name: 'barye',
    dimension: 'pressure',
    label: 'Barye',
    abbreviation: 'Ba',
    aliases: [
      'Ba',
      'barie',
      'barad',
      'barrie',
      'baryd'
    ],
    definition: '0.1 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'becquerel',
    dimension: 'frequency',
    label: 'Becquerel',
    abbreviation: 'Bq',
    aliases: [
      'Bq'
    ],
    definition: '1.0 / second',
    offset: 0.0
  },
  {
    name: 'biot',
    dimension: 'current',
    label: 'Biot',
    abbreviation: 'Bi',
    aliases: [
      'Bi'
    ],
    definition: '10 ampere',
    offset: 0.0
  },
  {
    name: 'bohr_magneton',
    dimension: 'magnetic_dipole',
    label: 'Bohr magneton',
    abbreviation: '\u00b5_B',
    aliases: [
      '\u00b5_B',
      'mu_B'
    ],
    definition: '9.274010078362164e-24 ampere * meter ^ 2',
    offset: 0.0
  },
  {
    name: 'boltzmann_constant',
    dimension: 'entropy',
    label: 'Boltzmann constant',
    abbreviation: 'k',
    aliases: [
      'k',
      'k_B'
    ],
    definition: '1.380649e-23 kilogram * meter ^ 2 / kelvin / second ^ 2',
    offset: 0.0
  },
  {
    name: 'buckingham',
    dimension: 'electric_quadrupole',
    label: 'Buckingham',
    abbreviation: 'buckingham',
    aliases: [],
    definition: '3.335640951981521e-40 ampere * meter ^ 2 * second',
    offset: 0.0
  },
  {
    name: 'byte',
    dimension: 'information',
    label: 'Byte',
    abbreviation: 'B',
    aliases: [
      'B',
      'octet'
    ],
    definition: '8 bit',
    offset: 0.0
  },
  {
    name: 'calorie',
    dimension: 'energy',
    label: 'Calorie',
    abbreviation: 'cal',
    aliases: [
      'cal',
      'thermochemical_calorie',
      'cal_th'
    ],
    definition: '4.184 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'carat',
    dimension: 'mass',
    label: 'Carat',
    abbreviation: 'ct',
    aliases: [
      'ct',
      'karat'
    ],
    definition: '0.0002 kilogram',
    offset: 0.0
  },
  {
    name: 'centimeter_H2O',
    dimension: 'pressure',
    label: 'Centimeter H2O',
    abbreviation: 'cmH2O',
    aliases: [
      'cmH2O',
      'cm_H2O'
    ],
    definition: '98.06649999999998 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'centimeter_Hg',
    dimension: 'pressure',
    label: 'Centimeter Hg',
    abbreviation: 'cmHg',
    aliases: [
      'cmHg',
      'cm_Hg',
      'centimeter_Hg_0C'
    ],
    definition: '1333.2238741499998 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'classical_electron_radius',
    dimension: 'length',
    label: 'Classical electron radius',
    abbreviation: 'r_e',
    aliases: [
      'r_e'
    ],
    definition: '2.817940326216153e-15 meter',
    offset: 0.0
  },
  {
    name: 'clausius',
    dimension: 'entropy',
    label: 'Clausius',
    abbreviation: 'Cl',
    aliases: [
      'Cl'
    ],
    definition: '4.184 kilogram * meter ^ 2 / kelvin / second ^ 2',
    offset: 0.0
  },
  {
    name: 'conductance_quantum',
    dimension: 'conductance',
    label: 'Conductance quantum',
    abbreviation: 'G_0',
    aliases: [
      'G_0'
    ],
    definition: '7.74809172986365e-05 ampere ^ 2 * second ^ 3 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'conventional_ampere_90',
    dimension: 'current',
    label: 'Conventional ampere 90',
    abbreviation: 'A_90',
    aliases: [
      'A_90'
    ],
    definition: '1.000000088871438 ampere',
    offset: 0.0
  },
  {
    name: 'conventional_coulomb_90',
    dimension: 'charge',
    label: 'Conventional coulomb 90',
    abbreviation: 'C_90',
    aliases: [
      'C_90'
    ],
    definition: '1.000000088871438 ampere * second',
    offset: 0.0
  },
  {
    name: 'conventional_farad_90',
    dimension: 'capacitance',
    label: 'Conventional farad 90',
    abbreviation: 'F_90',
    aliases: [
      'F_90'
    ],
    definition: '0.9999999822063327 ampere ^ 2 * second ^ 4 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'conventional_henry_90',
    dimension: 'inductance',
    label: 'Conventional henry 90',
    abbreviation: 'H_90',
    aliases: [
      'H_90'
    ],
    definition: '1.0000000177936679 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'conventional_ohm_90',
    dimension: 'resistance',
    label: 'Conventional ohm 90',
    abbreviation: '\u03a9_90',
    aliases: [
      '\u03a9_90',
      'ohm_90'
    ],
    definition: '1.0000000177936679 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'conventional_volt_90',
    dimension: 'electric_potential',
    label: 'Conventional volt 90',
    abbreviation: 'V_90',
    aliases: [
      'V_90'
    ],
    definition: '1.0000001066651074 kilogram * meter ^ 2 / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'conventional_von_klitzing_constant',
    dimension: 'resistance',
    label: 'Conventional von klitzing constant',
    abbreviation: 'R_K90',
    aliases: [
      'R_K90'
    ],
    definition: '25812.807 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'conventional_watt_90',
    dimension: 'power',
    label: 'Conventional watt 90',
    abbreviation: 'W_90',
    aliases: [
      'W_90'
    ],
    definition: '1.0000001955365547 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'coulomb',
    dimension: 'charge',
    label: 'Coulomb',
    abbreviation: 'C',
    aliases: [
      'C'
    ],
    definition: '1 ampere * second',
    offset: 0.0
  },
  {
    name: 'counts_per_second',
    dimension: 'frequency',
    label: 'Counts per second',
    abbreviation: 'cps',
    aliases: [
      'cps'
    ],
    definition: '1.0 / second',
    offset: 0.0
  },
  {
    name: 'curie',
    dimension: 'frequency',
    label: 'Curie',
    abbreviation: 'Ci',
    aliases: [
      'Ci'
    ],
    definition: '37000000000.0 / second',
    offset: 0.0
  },
  {
    name: 'dalton',
    dimension: 'mass',
    label: 'Dalton',
    abbreviation: 'Da',
    aliases: [
      'Da'
    ],
    definition: '1.6605390666e-27 kilogram',
    offset: 0.0
  },
  {
    name: 'darcy',
    dimension: 'area',
    label: 'Darcy',
    abbreviation: 'darcy',
    aliases: [],
    definition: '9.86923266716013e-13 meter ^ 2',
    offset: 0.0
  },
  {
    name: 'debye',
    dimension: 'electric_dipole',
    label: 'Debye',
    abbreviation: 'D',
    aliases: [
      'D'
    ],
    definition: '3.335640951981521e-30 ampere * meter * second',
    offset: 0.0
  },
  {
    name: 'degree',
    dimension: 'angle',
    label: 'Degree',
    abbreviation: '\u00b0',
    aliases: [
      '\u00b0',
      'deg',
      'arcdeg',
      'arcdegree',
      'angular_degree'
    ],
    definition: '0.017453292519943295 radian',
    offset: 0.0
  },
  {
    name: 'degree_Celsius',
    dimension: 'temperature',
    label: 'Degree Celsius',
    abbreviation: '\u00b0C',
    aliases: [
      '\u00b0C',
      'celsius',
      'degC',
      'degreeC'
    ],
    definition: '1 kelvin',
    offset: 273.15
  },
  {
    name: 'degree_Fahrenheit',
    dimension: 'temperature',
    label: 'Degree Fahrenheit',
    abbreviation: '\u00b0F',
    aliases: [
      '\u00b0F',
      'fahrenheit',
      'degF',
      'degreeF'
    ],
    definition: '0.5555555555555556 kelvin',
    offset: 459.67
  },
  {
    name: 'degree_Rankine',
    dimension: 'temperature',
    label: 'Degree Rankine',
    abbreviation: '\u00b0R',
    aliases: [
      '\u00b0R',
      'rankine',
      'degR',
      'degreeR'
    ],
    definition: '0.5555555555555556 kelvin',
    offset: 0.0
  },
  {
    name: 'degree_Reaumur',
    dimension: 'temperature',
    label: 'Degree Reaumur',
    abbreviation: '\u00b0Re',
    aliases: [
      '\u00b0Re',
      'reaumur',
      'degRe',
      'degreeRe',
      'degree_R\u00e9aumur',
      'r\u00e9aumur'
    ],
    definition: '0.8 kelvin',
    offset: 341.43749999999994
  },
  {
    name: 'dyne',
    dimension: 'force',
    label: 'Dyne',
    abbreviation: 'dyn',
    aliases: [
      'dyn'
    ],
    definition: '1e-05 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'electrical_horsepower',
    dimension: 'power',
    label: 'Electrical horsepower',
    abbreviation: 'electrical_horsepower',
    aliases: [],
    definition: '746.0 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'electron_mass',
    dimension: 'mass',
    label: 'Electron mass',
    abbreviation: 'm_e',
    aliases: [
      'm_e',
      'atomic_unit_of_mass',
      'a_u_mass'
    ],
    definition: '9.1093837015e-31 kilogram',
    offset: 0.0
  },
  {
    name: 'electron_volt',
    dimension: 'energy',
    label: 'Electron volt',
    abbreviation: 'eV',
    aliases: [
      'eV'
    ],
    definition: '1.602176634e-19 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'elementary_charge',
    dimension: 'charge',
    label: 'Elementary charge',
    abbreviation: 'e',
    aliases: [
      'e'
    ],
    definition: '1.602176634e-19 ampere * second',
    offset: 0.0
  },
  {
    name: 'entropy_unit',
    dimension: 'molar_entropy',
    label: 'Entropy unit',
    abbreviation: 'eu',
    aliases: [
      'eu'
    ],
    definition: '4.184 kilogram * meter ^ 2 / kelvin / mole / second ^ 2',
    offset: 0.0
  },
  {
    name: 'enzyme_unit',
    dimension: 'activity',
    label: 'Enzyme unit',
    abbreviation: 'U',
    aliases: [
      'U',
      'enzymeunit'
    ],
    definition: '1.6666666666666667e-08 mole / second',
    offset: 0.0
  },
  {
    name: 'erg',
    dimension: 'energy',
    label: 'Erg',
    abbreviation: 'erg',
    aliases: [],
    definition: '1.0000000000000001e-07 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'farad',
    dimension: 'capacitance',
    label: 'Farad',
    abbreviation: 'F',
    aliases: [
      'F'
    ],
    definition: '1.0 ampere ^ 2 * second ^ 4 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'faraday',
    dimension: 'charge',
    label: 'Faraday',
    abbreviation: 'faraday',
    aliases: [],
    definition: '96485.33212331001 ampere * second',
    offset: 0.0
  },
  {
    name: 'femtosecond',
    dimension: 'time',
    label: 'Femtosecond',
    abbreviation: 'fs',
    definition: '1e-15 second',
    offset: 0.0
  },
  {
    name: 'fermi',
    dimension: 'length',
    label: 'Fermi',
    abbreviation: 'fermi',
    aliases: [],
    definition: '1e-15 meter',
    offset: 0.0
  },
  {
    name: 'fifteen_degree_calorie',
    dimension: 'energy',
    label: 'Fifteen degree calorie',
    abbreviation: 'cal_15',
    aliases: [
      'cal_15'
    ],
    definition: '4.1855 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'foot_H2O',
    dimension: 'pressure',
    label: 'Foot H2O',
    abbreviation: 'ftH2O',
    aliases: [
      'ftH2O',
      'feet_H2O'
    ],
    definition: '2989.0669199999993 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'foot_per_second',
    dimension: 'speed',
    label: 'Foot per second',
    abbreviation: 'fps',
    aliases: [
      'fps'
    ],
    definition: '0.30479999999999996 meter / second',
    offset: 0.0
  },
  {
    name: 'force_gram',
    dimension: 'force',
    label: 'Force gram',
    abbreviation: 'gf',
    aliases: [
      'gf',
      'gram_force'
    ],
    definition: '0.00980665 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'force_kilogram',
    dimension: 'force',
    label: 'Force kilogram',
    abbreviation: 'pond',
    aliases: [
      'pond'
    ],
    definition: '9.80665 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'force_metric_ton',
    dimension: 'force',
    label: 'Force metric ton',
    abbreviation: 'tf',
    aliases: [
      'tf',
      'metric_ton_force',
      'force_t',
      't_force'
    ],
    definition: '9806.65 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'galileo',
    dimension: 'acceleration',
    label: 'Galileo',
    abbreviation: 'Gal',
    aliases: [
      'Gal'
    ],
    definition: '0.01 meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'gamma',
    dimension: 'magnetic_field',
    label: 'Gamma',
    abbreviation: '\u03b3',
    aliases: [
      '\u03b3'
    ],
    definition: '1.0000000000000003e-09 kilogram / ampere / second ^ 2',
    offset: 0.0
  },
  {
    name: 'gamma_mass',
    dimension: 'mass',
    label: 'Gamma mass',
    abbreviation: 'gamma_mass',
    aliases: [],
    definition: '1e-09 kilogram',
    offset: 0.0
  },
  {
    name: 'gigapascal',
    dimension: 'pressure',
    label: 'Gigapascal',
    abbreviation: 'GPa',
    definition: '1000000000.0 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'grade',
    dimension: 'angle',
    label: 'Grade',
    abbreviation: 'grad',
    aliases: [
      'grad',
      'gon'
    ],
    definition: '0.015707963267948967 radian',
    offset: 0.0
  },
  {
    name: 'grain',
    dimension: 'mass',
    label: 'Grain',
    abbreviation: 'gr',
    aliases: [
      'gr'
    ],
    definition: '6.479891000000001e-05 kilogram',
    offset: 0.0
  },
  {
    name: 'gram',
    dimension: 'mass',
    label: 'Gram',
    abbreviation: 'g',
    aliases: [
      'g'
    ],
    definition: '0.001 kilogram',
    offset: 0.0
  },
  {
    name: 'hartree',
    dimension: 'energy',
    label: 'Hartree',
    abbreviation: 'Ha',
    aliases: [
      'Ha',
      'E_h',
      'hartree_energy',
      'atomic_unit_of_energy',
      'a_u_energy'
    ],
    definition: '4.35974472220717e-18 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'henry',
    dimension: 'inductance',
    label: 'Henry',
    abbreviation: 'H',
    aliases: [
      'H'
    ],
    definition: '1.0 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'hertz',
    dimension: 'frequency',
    label: 'Hertz',
    abbreviation: 'Hz',
    aliases: [
      'Hz'
    ],
    definition: '1.0 / second',
    offset: 0.0
  },
  {
    name: 'horsepower',
    dimension: 'power',
    label: 'Horsepower',
    abbreviation: 'hp',
    aliases: [
      'hp',
      'UK_horsepower',
      'hydraulic_horsepower'
    ],
    definition: '745.6998715822701 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'hour',
    dimension: 'time',
    label: 'Hour',
    abbreviation: 'hr',
    aliases: [
      'hr'
    ],
    definition: '3600 second',
    offset: 0.0
  },
  {
    name: 'impedance_of_free_space',
    dimension: 'resistance',
    label: 'Impedance of free space',
    abbreviation: 'Z_0',
    aliases: [
      'Z_0',
      'characteristic_impedance_of_vacuum'
    ],
    definition: '376.73031366837046 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'inch_H2O_39F',
    dimension: 'pressure',
    label: 'Inch H2O 39F',
    abbreviation: 'inch_H2O_39F',
    aliases: [],
    definition: '249.08193551052 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'inch_H2O_60F',
    dimension: 'pressure',
    label: 'Inch H2O 60F',
    abbreviation: 'inch_H2O_60F',
    aliases: [],
    definition: '248.84007017890997 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'inch_Hg',
    dimension: 'pressure',
    label: 'Inch Hg',
    abbreviation: 'inHg',
    aliases: [
      'inHg',
      'in_Hg',
      'inch_Hg_32F'
    ],
    definition: '3386.3886403409997 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'inch_Hg_60F',
    dimension: 'pressure',
    label: 'Inch Hg 60F',
    abbreviation: 'inch_Hg_60F',
    aliases: [],
    definition: '3376.8485350879996 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'international_calorie',
    dimension: 'energy',
    label: 'International calorie',
    abbreviation: 'cal_it',
    aliases: [
      'cal_it',
      'international_steam_table_calorie'
    ],
    definition: '4.1868 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'joule',
    dimension: 'energy',
    label: 'Joule',
    abbreviation: 'J',
    aliases: [
      'J'
    ],
    definition: '1.0 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'katal',
    dimension: 'activity',
    label: 'Katal',
    abbreviation: 'kat',
    aliases: [
      'kat'
    ],
    definition: '1.0 mole / second',
    offset: 0.0
  },
  {
    name: 'kilometer_per_hour',
    dimension: 'speed',
    label: 'Kilometer per hour',
    abbreviation: 'kph',
    aliases: [
      'kph',
      'KPH'
    ],
    definition: '0.2777777777777778 meter / second',
    offset: 0.0
  },
  {
    name: 'kilometer_per_second',
    dimension: 'speed',
    label: 'Kilometer per second',
    abbreviation: 'kmps',
    aliases: [
      'kps'
    ],
    definition: '1000.0 meter / second',
    offset: 0.0
  },
  {
    name: 'kip_per_square_inch',
    dimension: 'pressure',
    label: 'Kip per square inch',
    abbreviation: 'ksi',
    aliases: [
      'ksi'
    ],
    definition: '6894757.293168365 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'lambda',
    dimension: 'volume',
    label: 'Lambda',
    abbreviation: '\u03bb',
    aliases: [
      '\u03bb'
    ],
    definition: '1.0000000000000003e-09 meter ^ 3',
    offset: 0.0
  },
  {
    name: 'lambert',
    dimension: 'luminance',
    label: 'Lambert',
    abbreviation: 'lambert',
    aliases: [],
    definition: '3183.098861837907 candela / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'liter',
    dimension: 'volume',
    label: 'Liter',
    abbreviation: 'l',
    aliases: [
      'l',
      'L',
      'litre'
    ],
    definition: '0.0010000000000000002 meter ^ 3',
    offset: 0.0
  },
  {
    name: 'lumen',
    dimension: 'luminous_flux',
    label: 'Lumen',
    abbreviation: 'lm',
    aliases: [
      'lm'
    ],
    definition: '1 candela * radian ^ 2',
    offset: 0.0
  },
  {
    name: 'lux',
    dimension: 'illuminance',
    label: 'Lux',
    abbreviation: 'lx',
    aliases: [
      'lx'
    ],
    definition: '1.0 candela * radian ^ 2 / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'magnetic_flux_quantum',
    dimension: 'magnetic_flux',
    label: 'Magnetic flux quantum',
    abbreviation: '\u03a6_0',
    aliases: [
      '\u03a6_0',
      'Phi_0'
    ],
    definition: '2.0678338484619295e-15 kilogram * meter ^ 2 / ampere / second ^ 2',
    offset: 0.0
  },
  {
    name: 'mean_international_ampere',
    dimension: 'current',
    label: 'Mean international ampere',
    abbreviation: 'A_it',
    aliases: [
      'A_it'
    ],
    definition: '0.9998500734640026 ampere',
    offset: 0.0
  },
  {
    name: 'mean_international_ohm',
    dimension: 'resistance',
    label: 'Mean international ohm',
    abbreviation: '\u03a9_it',
    aliases: [
      '\u03a9_it',
      'ohm_it'
    ],
    definition: '1.00049 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'mean_international_volt',
    dimension: 'electric_potential',
    label: 'Mean international volt',
    abbreviation: 'V_it',
    aliases: [
      'V_it'
    ],
    definition: '1.00034 kilogram * meter ^ 2 / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'mercury',
    dimension: 'density',
    label: 'Mercury',
    abbreviation: 'Hg',
    aliases: [
      'Hg',
      'Hg_0C',
      'Hg_32F',
      'conventional_mercury'
    ],
    definition: '13595.099999999999 kilogram / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'mercury_60F',
    dimension: 'density',
    label: 'Mercury 60F',
    abbreviation: 'Hg_60F',
    aliases: [
      'Hg_60F'
    ],
    definition: '13556.800000000001 kilogram / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'meter_per_second',
    dimension: 'speed',
    label: 'Meter per second',
    abbreviation: 'mps',
    aliases: [
      'mps'
    ],
    definition: '1.0 meter / second',
    offset: 0.0
  },
  {
    name: 'metric_horsepower',
    dimension: 'power',
    label: 'Metric horsepower',
    abbreviation: 'metric_horsepower',
    aliases: [],
    definition: '735.49875 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'metric_ton',
    dimension: 'mass',
    label: 'Metric ton',
    abbreviation: 'tonne',
    aliases: [
      'tonne'
    ],
    definition: '1000.0 kilogram',
    offset: 0.0
  },
  {
    name: 'micron',
    dimension: 'length',
    label: 'Micron',
    abbreviation: '\u00b5',
    aliases: [
      '\u00b5'
    ],
    definition: '1e-06 meter',
    offset: 0.0
  },
  {
    name: 'mil',
    dimension: 'angle',
    label: 'Mil',
    abbreviation: 'mil',
    aliases: [],
    definition: '9.817477042468104e-05 radian',
    offset: 0.0
  },
  {
    name: 'mile_per_hour',
    dimension: 'speed',
    label: 'Mile per hour',
    abbreviation: 'mph',
    aliases: [
      'mph',
      'MPH'
    ],
    definition: '0.44704000000000005 meter / second',
    offset: 0.0
  },
  {
    name: 'milliarcsecond',
    dimension: 'angle',
    label: 'Milliarcsecond',
    abbreviation: 'marcsec',
    aliases: [
      'mas'
    ],
    definition: '4.84813681109536e-09 radian',
    offset: 0.0
  },
  {
    name: 'millibar',
    dimension: 'pressure',
    label: 'Millibar',
    abbreviation: 'mbar',
    definition: '100.0 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'millimeter_Hg',
    dimension: 'pressure',
    label: 'Millimeter Hg',
    abbreviation: 'mmHg',
    aliases: [
      'mmHg',
      'mm_Hg',
      'millimeter_Hg_0C'
    ],
    definition: '133.32238741499998 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'minute',
    dimension: 'time',
    label: 'Minute',
    abbreviation: 'minute',
    aliases: [],
    definition: '60 second',
    offset: 0.0
  },
  {
    name: 'molar',
    dimension: 'concentration',
    label: 'Molar',
    abbreviation: 'M',
    aliases: [
      'M'
    ],
    definition: '999.9999999999999 mole / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'molar_gas_constant',
    dimension: 'molar_entropy',
    label: 'Molar gas constant',
    abbreviation: 'R',
    aliases: [
      'R'
    ],
    definition: '8.314462618153241 kilogram * meter ^ 2 / kelvin / mole / second ^ 2',
    offset: 0.0
  },
  {
    name: 'neutron_mass',
    dimension: 'mass',
    label: 'Neutron mass',
    abbreviation: 'm_n',
    aliases: [
      'm_n'
    ],
    definition: '1.67492749804e-27 kilogram',
    offset: 0.0
  },
  {
    name: 'newton',
    dimension: 'force',
    label: 'Newton',
    abbreviation: 'N',
    aliases: [
      'N'
    ],
    definition: '1.0 kilogram * meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'nit',
    dimension: 'luminance',
    label: 'Nit',
    abbreviation: 'nit',
    aliases: [],
    definition: '1.0 candela / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'nuclear_magneton',
    dimension: 'magnetic_dipole',
    label: 'Nuclear magneton',
    abbreviation: '\u00b5_N',
    aliases: [
      '\u00b5_N',
      'mu_N'
    ],
    definition: '5.050783746096374e-27 ampere * meter ^ 2',
    offset: 0.0
  },
  {
    name: 'ohm',
    dimension: 'resistance',
    label: 'Ohm',
    abbreviation: '\u03a9',
    aliases: [
      '\u03a9'
    ],
    definition: '1.0 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'particle',
    dimension: 'substance',
    label: 'Particle',
    abbreviation: 'particle',
    aliases: [
      'molec',
      'molecule'
    ],
    definition: '1.6605390671738466e-24 mole',
    offset: 0.0
  },
  {
    name: 'pascal',
    dimension: 'pressure',
    label: 'Pascal',
    abbreviation: 'Pa',
    aliases: [
      'Pa'
    ],
    definition: '1.0 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'pixels_per_centimeter',
    dimension: 'pixel_density',
    label: 'Pixels per centimeter',
    abbreviation: 'PPCM',
    aliases: [
      'PPCM',
      'ppcm'
    ],
    definition: '100.0 pixel / meter',
    offset: 0.0
  },
  {
    name: 'pixels_per_inch',
    dimension: 'pixel_density',
    label: 'Pixels per inch',
    abbreviation: 'PPI',
    aliases: [
      'PPI',
      'ppi'
    ],
    definition: '39.37007874015748 pixel / meter',
    offset: 0.0
  },
  {
    name: 'planck_current',
    dimension: 'current',
    label: 'Planck current',
    abbreviation: 'planck_current',
    aliases: [],
    definition: '3.478872753744379e+25 ampere',
    offset: 0.0
  },
  {
    name: 'planck_length',
    dimension: 'length',
    label: 'Planck length',
    abbreviation: 'planck_length',
    aliases: [],
    definition: '1.616255024423705e-35 meter',
    offset: 0.0
  },
  {
    name: 'planck_mass',
    dimension: 'mass',
    label: 'Planck mass',
    abbreviation: 'planck_mass',
    aliases: [],
    definition: '2.1764343427178987e-08 kilogram',
    offset: 0.0
  },
  {
    name: 'planck_temperature',
    dimension: 'temperature',
    label: 'Planck temperature',
    abbreviation: 'planck_temperature',
    aliases: [],
    definition: '1.4167841621573425e+32 kelvin',
    offset: 0.0
  },
  {
    name: 'planck_time',
    dimension: 'time',
    label: 'Planck time',
    abbreviation: 'planck_time',
    aliases: [],
    definition: '5.391246448313604e-44 second',
    offset: 0.0
  },
  {
    name: 'poise',
    dimension: 'viscosity',
    label: 'Poise',
    abbreviation: 'P',
    aliases: [
      'P'
    ],
    definition: '0.1 kilogram / meter / second',
    offset: 0.0
  },
  {
    name: 'pound_force_per_square_inch',
    dimension: 'pressure',
    label: 'Pound force per square inch',
    abbreviation: 'psi',
    aliases: [
      'psi'
    ],
    definition: '6894.7572931683635 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'proton_mass',
    dimension: 'mass',
    label: 'Proton mass',
    abbreviation: 'm_p',
    aliases: [
      'm_p'
    ],
    definition: '1.67262192369e-27 kilogram',
    offset: 0.0
  },
  {
    name: 'reciprocal_centimeter',
    dimension: 'wavenumber',
    label: 'Reciprocal centimeter',
    abbreviation: 'cm_1',
    aliases: [
      'cm_1',
      'kayser'
    ],
    definition: '100.0 / meter',
    offset: 0.0
  },
  {
    name: 'revolutions_per_minute',
    dimension: 'frequency',
    label: 'Revolutions per minute',
    abbreviation: 'rpm',
    aliases: [
      'rpm'
    ],
    definition: '0.016666666666666666 / second',
    offset: 0.0
  },
  {
    name: 'revolutions_per_second',
    dimension: 'frequency',
    label: 'Revolutions per second',
    abbreviation: 'rps',
    aliases: [
      'rps'
    ],
    definition: '1.0 / second',
    offset: 0.0
  },
  {
    name: 'reyn',
    dimension: 'viscosity',
    label: 'Reyn',
    abbreviation: 'reyn',
    aliases: [],
    definition: '6894.7572931683635 kilogram / meter / second',
    offset: 0.0
  },
  {
    name: 'rhe',
    dimension: 'fluidity',
    label: 'Rhe',
    abbreviation: 'rhe',
    aliases: [],
    definition: '10.0 meter * second / kilogram',
    offset: 0.0
  },
  {
    name: 'rutherford',
    dimension: 'frequency',
    label: 'Rutherford',
    abbreviation: 'Rd',
    aliases: [
      'Rd'
    ],
    definition: '1000000.0 / second',
    offset: 0.0
  },
  {
    name: 'rydberg',
    dimension: 'energy',
    label: 'Rydberg',
    abbreviation: 'Ry',
    aliases: [
      'Ry'
    ],
    definition: '2.179872361103585e-18 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'rydberg_constant',
    dimension: 'wavenumber',
    label: 'Rydberg constant',
    abbreviation: 'R_\u221e',
    aliases: [
      'R_\u221e',
      'R_inf'
    ],
    definition: '10973731.56816 / meter',
    offset: 0.0
  },
  {
    name: 'siemens',
    dimension: 'conductance',
    label: 'Siemens',
    abbreviation: 'S',
    aliases: [
      'S',
      'mho'
    ],
    definition: '1.0 ampere ^ 2 * second ^ 3 / kilogram / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'speed_of_light',
    dimension: 'speed',
    label: 'Speed of light',
    abbreviation: 'c',
    aliases: [
      'c',
      'c_0'
    ],
    definition: '299792458.0 meter / second',
    offset: 0.0
  },
  {
    name: 'standard_atmosphere',
    dimension: 'pressure',
    label: 'Standard atmosphere',
    abbreviation: 'atm',
    aliases: [
      'atm',
      'atmosphere'
    ],
    definition: '101325.0 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'standard_gravity',
    dimension: 'acceleration',
    label: 'Standard gravity',
    abbreviation: 'g_0',
    aliases: [
      'g_0',
      'g0',
      'g_n',
      'gravity'
    ],
    definition: '9.80665 meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'standard_liter_per_minute',
    dimension: 'power',
    label: 'Standard liter per minute',
    abbreviation: 'slpm',
    aliases: [
      'slpm',
      'slm'
    ],
    definition: '1.6887500000000004 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'stilb',
    dimension: 'luminance',
    label: 'Stilb',
    abbreviation: 'stilb',
    aliases: [],
    definition: '10000.0 candela / meter ^ 2',
    offset: 0.0
  },
  {
    name: 'stokes',
    dimension: 'kinematic_viscosity',
    label: 'Stokes',
    abbreviation: 'St',
    aliases: [
      'St'
    ],
    definition: '0.0001 meter ^ 2 / second',
    offset: 0.0
  },
  {
    name: 'tesla',
    dimension: 'magnetic_field',
    label: 'Tesla',
    abbreviation: 'T',
    aliases: [
      'T'
    ],
    definition: '1.0 kilogram / ampere / second ^ 2',
    offset: 0.0
  },
  {
    name: 'thomson_cross_section',
    dimension: 'area',
    label: 'Thomson cross section',
    abbreviation: '\u03c3_e',
    aliases: [
      '\u03c3_e',
      'sigma_e'
    ],
    definition: '6.652458732226516e-29 meter ^ 2',
    offset: 0.0
  },
  {
    name: 'torr',
    dimension: 'pressure',
    label: 'Torr',
    abbreviation: 'torr',
    aliases: [],
    definition: '133.32236842105263 kilogram / meter / second ^ 2',
    offset: 0.0
  },
  {
    name: 'unified_atomic_mass_unit',
    dimension: 'mass',
    label: 'Unified atomic mass unit',
    abbreviation: 'u',
    aliases: [
      'u',
      'amu'
    ],
    definition: '1.6605390666e-27 kilogram',
    offset: 0.0
  },
  {
    name: 'unit_pole',
    dimension: 'magnetic_flux',
    label: 'Unit pole',
    abbreviation: 'unit_pole',
    aliases: [],
    definition: '1.2566370621250598e-07 kilogram * meter ^ 2 / ampere / second ^ 2',
    offset: 0.0
  },
  {
    name: 'volt',
    dimension: 'electric_potential',
    label: 'Volt',
    abbreviation: 'V',
    aliases: [
      'V'
    ],
    definition: '1.0 kilogram * meter ^ 2 / ampere / second ^ 3',
    offset: 0.0
  },
  {
    name: 'volt_ampere',
    dimension: 'power',
    label: 'Volt ampere',
    abbreviation: 'VA',
    aliases: [
      'VA'
    ],
    definition: '1.0 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'von_klitzing_constant',
    dimension: 'resistance',
    label: 'Von klitzing constant',
    abbreviation: 'R_K',
    aliases: [
      'R_K'
    ],
    definition: '25812.807459304513 kilogram * meter ^ 2 / ampere ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'water',
    dimension: 'density',
    label: 'Water',
    abbreviation: 'H2O',
    aliases: [
      'H2O',
      'conventional_water'
    ],
    definition: '999.9999999999999 kilogram / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'water_39F',
    dimension: 'density',
    label: 'Water 39F',
    abbreviation: 'water_4C',
    aliases: [
      'water_4C'
    ],
    definition: '999.9719999999999 kilogram / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'water_60F',
    dimension: 'density',
    label: 'Water 60F',
    abbreviation: 'water_60F',
    aliases: [],
    definition: '999.0009999999999 kilogram / meter ^ 3',
    offset: 0.0
  },
  {
    name: 'watt',
    dimension: 'power',
    label: 'Watt',
    abbreviation: 'W',
    aliases: [
      'W'
    ],
    definition: '1.0 kilogram * meter ^ 2 / second ^ 3',
    offset: 0.0
  },
  {
    name: 'watt_hour',
    dimension: 'energy',
    label: 'Watt hour',
    abbreviation: 'Wh',
    aliases: [
      'Wh',
      'watthour'
    ],
    definition: '3600.0 kilogram * meter ^ 2 / second ^ 2',
    offset: 0.0
  },
  {
    name: 'weber',
    dimension: 'magnetic_flux',
    label: 'Weber',
    abbreviation: 'Wb',
    aliases: [
      'Wb'
    ],
    definition: '1.0 kilogram * meter ^ 2 / ampere / second ^ 2',
    offset: 0.0
  }
]
export const prefixes = {
  '': {
    name: '',
    value: 1,
    scientific: true
  },
  yocto: {
    name: 'yocto',
    value: 1e-24,
    scientific: true
  },
  y: {
    name: 'y',
    value: 1e-24,
    scientific: true
  },
  zepto: {
    name: 'zepto',
    value: 1e-21,
    scientific: true
  },
  z: {
    name: 'z',
    value: 1e-21,
    scientific: true
  },
  atto: {
    name: 'atto',
    value: 1e-18,
    scientific: true
  },
  a: {
    name: 'a',
    value: 1e-18,
    scientific: true
  },
  femto: {
    name: 'femto',
    value: 1e-15,
    scientific: true
  },
  f: {
    name: 'f',
    value: 1e-15,
    scientific: true
  },
  pico: {
    name: 'pico',
    value: 1e-12,
    scientific: true
  },
  p: {
    name: 'p',
    value: 1e-12,
    scientific: true
  },
  nano: {
    name: 'nano',
    value: 1e-09,
    scientific: true
  },
  n: {
    name: 'n',
    value: 1e-09,
    scientific: true
  },
  micro: {
    name: 'micro',
    value: 1e-06,
    scientific: true
  },
  \u00b5: {
    name: '\u00b5',
    value: 1e-06,
    scientific: true
  },
  u: {
    name: 'u',
    value: 1e-06,
    scientific: true
  },
  milli: {
    name: 'milli',
    value: 0.001,
    scientific: true
  },
  m: {
    name: 'm',
    value: 0.001,
    scientific: true
  },
  centi: {
    name: 'centi',
    value: 0.01,
    scientific: true
  },
  c: {
    name: 'c',
    value: 0.01,
    scientific: true
  },
  deci: {
    name: 'deci',
    value: 0.1,
    scientific: true
  },
  d: {
    name: 'd',
    value: 0.1,
    scientific: true
  },
  deca: {
    name: 'deca',
    value: 10.0,
    scientific: true
  },
  da: {
    name: 'da',
    value: 10.0,
    scientific: true
  },
  deka: {
    name: 'deka',
    value: 10.0,
    scientific: true
  },
  hecto: {
    name: 'hecto',
    value: 100.0,
    scientific: true
  },
  h: {
    name: 'h',
    value: 100.0,
    scientific: true
  },
  kilo: {
    name: 'kilo',
    value: 1000.0,
    scientific: true
  },
  k: {
    name: 'k',
    value: 1000.0,
    scientific: true
  },
  mega: {
    name: 'mega',
    value: 1000000.0,
    scientific: true
  },
  M: {
    name: 'M',
    value: 1000000.0,
    scientific: true
  },
  giga: {
    name: 'giga',
    value: 1000000000.0,
    scientific: true
  },
  G: {
    name: 'G',
    value: 1000000000.0,
    scientific: true
  },
  tera: {
    name: 'tera',
    value: 1000000000000.0,
    scientific: true
  },
  T: {
    name: 'T',
    value: 1000000000000.0,
    scientific: true
  },
  peta: {
    name: 'peta',
    value: 1000000000000000.0,
    scientific: true
  },
  P: {
    name: 'P',
    value: 1000000000000000.0,
    scientific: true
  },
  exa: {
    name: 'exa',
    value: 1e+18,
    scientific: true
  },
  E: {
    name: 'E',
    value: 1e+18,
    scientific: true
  },
  zetta: {
    name: 'zetta',
    value: 1e+21,
    scientific: true
  },
  Z: {
    name: 'Z',
    value: 1e+21,
    scientific: true
  },
  yotta: {
    name: 'yotta',
    value: 1e+24,
    scientific: true
  },
  Y: {
    name: 'Y',
    value: 1e+24,
    scientific: true
  },
  kibi: {
    name: 'kibi',
    value: 1024,
    scientific: true
  },
  Ki: {
    name: 'Ki',
    value: 1024,
    scientific: true
  },
  mebi: {
    name: 'mebi',
    value: 1048576,
    scientific: true
  },
  Mi: {
    name: 'Mi',
    value: 1048576,
    scientific: true
  },
  gibi: {
    name: 'gibi',
    value: 1073741824,
    scientific: true
  },
  Gi: {
    name: 'Gi',
    value: 1073741824,
    scientific: true
  },
  tebi: {
    name: 'tebi',
    value: 1099511627776,
    scientific: true
  },
  Ti: {
    name: 'Ti',
    value: 1099511627776,
    scientific: true
  },
  pebi: {
    name: 'pebi',
    value: 1125899906842624,
    scientific: true
  },
  Pi: {
    name: 'Pi',
    value: 1125899906842624,
    scientific: true
  },
  exbi: {
    name: 'exbi',
    value: 1152921504606846976,
    scientific: true
  },
  Ei: {
    name: 'Ei',
    value: 1152921504606846976,
    scientific: true
  },
  zebi: {
    name: 'zebi',
    value: 1180591620717411303424,
    scientific: true
  },
  Zi: {
    name: 'Zi',
    value: 1180591620717411303424,
    scientific: true
  },
  yobi: {
    name: 'yobi',
    value: 1208925819614629174706176,
    scientific: true
  },
  Yi: {
    name: 'Yi',
    value: 1208925819614629174706176,
    scientific: true
  }
}
