Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Na             3s            0.22            0.33
                         total            0.22            0.33

      2      Na             3s            0.22            0.33
                         total            0.22            0.33

      3      Na             3s            0.22            0.33
                         total            0.22            0.33

      4      Na             3s            0.22            0.33
                         total            0.22            0.33

      5      Cl             3s            1.94            1.87
                          3p_y            1.95            1.93
                          3p_z            1.95            1.93
                          3p_x            1.95            1.93
                         total            7.78            7.67

      6      Cl             3s            1.94            1.87
                          3p_y            1.95            1.93
                          3p_z            1.95            1.93
                          3p_x            1.95            1.93
                         total            7.78            7.67

      7      Cl             3s            1.94            1.87
                          3p_y            1.95            1.93
                          3p_z            1.95            1.93
                          3p_x            1.95            1.93
                         total            7.78            7.67

      8      Cl             3s            1.94            1.87
                          3p_y            1.95            1.93
                          3p_z            1.95            1.93
                          3p_x            1.95            1.93
                         total            7.78            7.67

