GET http://localhost/nomad/api/uploads  HTTP/1.1

###

POST http://localhost/nomad/api/uploads  HTTP/1.1
content-type: application/json

{
    "name": "aims-example-full"
}
###

GET http://localhost:8000/nomad/api/v2/uploads/ HTTP/1.1
Authorization: Basic bGVvbmFyZC5ob2ZzdGFkdGVyQG5vbWFkLWZhaXJkaS50ZXN0cy5kZTo=
###


GET http://localhost:9200/test_nomad_fairdi_calcs/_search HTTP/1.1
###

DELETE http://localhost:9200/nomad_fairdi_calcs HTTP/1.1
###


DELETE http://localhost:9200/nomad_fairdi_test HTTP/1.1