DELETE http://localhost:9200/repo_index HTTP/1.1;

###
DELETE http://localhost:9200/repo_topics HTTP/1.1;

###
GET http://localhost:9200/_cat/indices HTTP/1.1;

###
GET http://localhost:9200/repo_index/_search HTTP/1.1;


###
POST http://localhost:8111/repo/repo-update/index/calculation HTTP/1.1;
content-type: application/json

{
    "calc_ids": [13]
}


###
POST http://localhost:8000/nomad/api/uploads/9SRMChG9SZCyqBeigPM2Hg HTTP/1.1;
content-type: application/json
Authorization: Basic bGVvbmFyZC5ob2ZzdGFkdGVyQG5vbWFkLWZhaXJkaS50ZXN0cy5kZTpub21hZA==

{
    "operation": "unstage"
}