<?xml version="1.0" encoding="UTF-8"?>
<fpmd:simulation xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">

                   ============================
                   I qbox 1.63.2              I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I                          I
                   I http://qboxcode.org      I
                   ============================


<release> 1.63.2 dell </release>
<sysname> Linux </sysname>
<nodename> theobook68 </nodename>
<start_time> 2016-04-06T12:24:19Z </start_time>
<mpi_processes count="4">
<process id="0"> theobook68 </process>
<process id="1"> theobook68 </process>
<process id="2"> theobook68 </process>
<process id="3"> theobook68 </process>
</mpi_processes>
[qbox] <cmd>set cell 16 0 0  0 16 0  0 0 16</cmd>
<unit_cell 
    a="16.00000000  0.00000000   0.00000000  "
    b="0.00000000   16.00000000  0.00000000  "
    c="0.00000000   0.00000000   16.00000000 " />
[qbox] <cmd>species oxygen O_HSCV_PBE-1.0.xml</cmd>
  SpeciesCmd: defining species oxygen as O_HSCV_PBE-1.0.xml

 species oxygen:
<species name="oxygen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV O xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:25:11Z
 psgen arguments:
 -element O -xc PBE -smooth_v -bound l=0:rc=0.8 -bound l=1:rc=0.8
 </description>
 <symbol>O</symbol>
 <atomic_number>8</atomic_number>
 <mass>15.99940000</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>6</valence_charge>
 <lmax>1</lmax>
 <llocal>1</llocal>
 <nquad>0</nquad>
 <rquad>0.00000000</rquad>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 Kleinman-Bylander potential
 rcps_ =   1.50000000
[qbox] <cmd>species hydrogen H_HSCV_PBE-1.0.xml</cmd>
  SpeciesCmd: defining species hydrogen as H_HSCV_PBE-1.0.xml

 species hydrogen:
<species name="hydrogen">
 <description>
 PSGen-1.6.0 pseudopotential: HSCV H xc=PBE
 Generated by PSGen-1.6.0 on 2009-02-15T02:24:50Z
 psgen arguments:
 -element H -xc PBE -smooth_v -bound l=0:rc=0.5
 </description>
 <symbol>H</symbol>
 <atomic_number>1</atomic_number>
 <mass>1.00794000</mass>
 <norm_conserving_pseudopotential>
 <valence_charge>1</valence_charge>
 <lmax>0</lmax>
 <llocal>0</llocal>
 <nquad>0</nquad>
 <rquad>0.00000000</rquad>
 <mesh_spacing>0.01000000</mesh_spacing>
 </norm_conserving_pseudopotential>
</species>
 local potential
 rcps_ =   1.50000000
[qbox] <cmd>atom O oxygen 0 0 0</cmd>
[qbox] <cmd>atom H1 hydrogen  1.128  1.444  0.000</cmd>
[qbox] <cmd>atom H2 hydrogen  1.128 -1.444  0.000</cmd>
[qbox] [qbox] <cmd>distance O H1</cmd>
 distance O-H1: 1.832 (a.u.) / 0.970 (Ang)
[qbox] <cmd>distance O H2</cmd>
 distance O-H2: 1.832 (a.u.) / 0.970 (Ang)
[qbox] <cmd>angle H1 O H2</cmd>
 angle H1-O-H2: 104.009 (deg)
[qbox] [qbox] <cmd>set ecut 70</cmd>
[qbox] <cmd>set wf_dyn PSDA</cmd>
[qbox] <cmd>set ecutprec 5</cmd>
[qbox] <cmd>randomize_wf</cmd>
[qbox] <cmd>run 0 100</cmd>
  EnergyFunctional: np0v,np1v,np2v: 90 90 90
  EnergyFunctional: vft->np012(): 729000
<wavefunction ecut="35.000" nspin="1" nel="8" nempty="0">
<cell a="16.000000 0.000000 0.000000"
      b="0.000000 16.000000 0.000000"
      c="0.000000 0.000000 16.000000"/>
 reciprocal lattice vectors
 0.392699 0.000000 0.000000
 0.000000 0.392699 0.000000
 0.000000 0.000000 0.392699
<refcell a="0.000000 0.000000 0.000000"
         b="0.000000 0.000000 0.000000"
         c="0.000000 0.000000 0.000000"/>
<grid nx="44" ny="44" nz="44"/>
 kpoint: 0.000000 0.000000 0.000000 weight: 1.000000
<slater_determinant kpoint="0.000000 0.000000 0.000000" size="4">
 sdcontext: 4x1
 basis size: 20242
 c dimensions: 20332x4   (5083x4 blocks)
 <density_matrix form="diagonal" size="4">
 </density_matrix>
</slater_determinant>
</wavefunction>
<iteration count="1">
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  57.74965306 </eigenvalue_sum>
  <etotal_int>     114.71460056 </etotal_int>
  total_electronic_charge: 7.99981707
  <eigenvalue_sum>  9.87922469 </eigenvalue_sum>
  Anderson extrapolation: theta=0.28374318 (0.28374318)
  <etotal_int>      19.43840546 </etotal_int>
  total_electronic_charge: 7.99999964
  <eigenvalue_sum>  -1.75693811 </eigenvalue_sum>
  Anderson extrapolation: theta=0.03112696 (0.03112696)
  <etotal_int>      -3.11870252 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.64082103 </eigenvalue_sum>
  Anderson extrapolation: theta=0.58842038 (0.58842038)
  <etotal_int>      -5.15462622 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.18376034 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.21670880 (-0.21670880)
  <etotal_int>      -6.40951469 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.33080737 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.97647173 (0.00000000)
  <etotal_int>      -6.80195262 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.66836170 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.47375597 (0.00000000)
  <etotal_int>      -7.73606688 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.11218821 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.89544480 (0.00000000)
  <etotal_int>      -9.21165686 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.45031072 </eigenvalue_sum>
  Anderson extrapolation: theta=0.70398648 (0.70398648)
  <etotal_int>     -10.87342875 </etotal_int>
  total_electronic_charge: 7.99999998
  <eigenvalue_sum>  -4.53350930 </eigenvalue_sum>
  Anderson extrapolation: theta=0.36387858 (0.36387858)
  <etotal_int>     -12.57033253 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.48706028 </eigenvalue_sum>
  Anderson extrapolation: theta=0.15615102 (0.15615102)
  <etotal_int>     -13.05343852 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.43592005 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.70630431 (-0.70630431)
  <etotal_int>     -13.25490537 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.43012741 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.18225723 (0.00000000)
  <etotal_int>     -13.27556288 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.37071724 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.61180998 (0.00000000)
  <etotal_int>     -13.45182859 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.29603376 </eigenvalue_sum>
  Anderson extrapolation: theta=-3.08007003 (0.00000000)
  <etotal_int>     -13.65527627 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.20523688 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.83898448 (0.00000000)
  <etotal_int>     -13.88946257 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -4.09922570 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.90293467 (0.00000000)
  <etotal_int>     -14.14859480 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.98265263 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.43290929 (-0.43290929)
  <etotal_int>     -14.41893730 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.91714502 </eigenvalue_sum>
  Anderson extrapolation: theta=1.75068935 (1.75068935)
  <etotal_int>     -14.57036288 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.68874485 </eigenvalue_sum>
  Anderson extrapolation: theta=1.03673044 (1.03673044)
  <etotal_int>     -15.05406507 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.45030850 </eigenvalue_sum>
  Anderson extrapolation: theta=0.84531809 (0.84531809)
  <etotal_int>     -15.56293490 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.40864626 </eigenvalue_sum>
  Anderson extrapolation: theta=0.25785962 (0.25785962)
  <etotal_int>     -15.82159157 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.41545925 </eigenvalue_sum>
  Anderson extrapolation: theta=0.43009448 (0.43009448)
  <etotal_int>     -15.87086009 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.40378217 </eigenvalue_sum>
  Anderson extrapolation: theta=0.64097691 (0.64097691)
  <etotal_int>     -15.90456757 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.37961920 </eigenvalue_sum>
  Anderson extrapolation: theta=0.44093518 (0.44093518)
  <etotal_int>     -15.94083656 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.35239035 </eigenvalue_sum>
  Anderson extrapolation: theta=0.36201712 (0.36201712)
  <etotal_int>     -15.97273077 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.32592496 </eigenvalue_sum>
  Anderson extrapolation: theta=-0.22995932 (-0.22995932)
  <etotal_int>     -16.00061263 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.31604273 </eigenvalue_sum>
  Anderson extrapolation: theta=-3.03671138 (0.00000000)
  <etotal_int>     -16.01079555 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.29901887 </eigenvalue_sum>
  Anderson extrapolation: theta=-2.38063895 (0.00000000)
  <etotal_int>     -16.02755307 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.28117565 </eigenvalue_sum>
  Anderson extrapolation: theta=-3.18184670 (0.00000000)
  <etotal_int>     -16.04460623 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.26244553 </eigenvalue_sum>
  Anderson extrapolation: theta=-3.85622057 (0.00000000)
  <etotal_int>     -16.06208142 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.24275396 </eigenvalue_sum>
  Anderson extrapolation: theta=-4.42929378 (0.00000000)
  <etotal_int>     -16.08011371 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.22201402 </eigenvalue_sum>
  Anderson extrapolation: theta=-4.92368659 (0.00000000)
  <etotal_int>     -16.09884921 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.20012302 </eigenvalue_sum>
  Anderson extrapolation: theta=-5.35540288 (0.00000000)
  <etotal_int>     -16.11844509 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.17696143 </eigenvalue_sum>
  Anderson extrapolation: theta=-5.73395943 (0.00000000)
  <etotal_int>     -16.13906727 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.15239446 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.06326723 (0.00000000)
  <etotal_int>     -16.16088572 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.12627665 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.34218179 (0.00000000)
  <etotal_int>     -16.18406729 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.09845946 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.56423883 (0.00000000)
  <etotal_int>     -16.20876610 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.06880195 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.71668507 (0.00000000)
  <etotal_int>     -16.23511161 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.03718453 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.77898603 (0.00000000)
  <etotal_int>     -16.26319505 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -3.00352481 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.72110961 (0.00000000)
  <etotal_int>     -16.29305527 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.96779497 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.50262094 (0.00000000)
  <etotal_int>     -16.32466573 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.93003784 </eigenvalue_sum>
  Anderson extrapolation: theta=-6.07384573 (0.00000000)
  <etotal_int>     -16.35792441 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.89038046 </eigenvalue_sum>
  Anderson extrapolation: theta=-5.38171137 (0.00000000)
  <etotal_int>     -16.39264898 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.84904146 </eigenvalue_sum>
  Anderson extrapolation: theta=-4.38156274 (0.00000000)
  <etotal_int>     -16.42857871 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.80633067 </eigenvalue_sum>
  Anderson extrapolation: theta=-3.05475747 (0.00000000)
  <etotal_int>     -16.46538412 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.76263907 </eigenvalue_sum>
  Anderson extrapolation: theta=-1.42583519 (0.00000000)
  <etotal_int>     -16.50268380 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.71841954 </eigenvalue_sum>
  Anderson extrapolation: theta=0.43059405 (0.43059405)
  <etotal_int>     -16.54006665 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.65455159 </eigenvalue_sum>
  Anderson extrapolation: theta=1.85414848 (1.85414848)
  <etotal_int>     -16.59289941 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.49021729 </eigenvalue_sum>
  Anderson extrapolation: theta=1.50164576 (1.50164576)
  <etotal_int>     -16.71901425 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.24615061 </eigenvalue_sum>
  Anderson extrapolation: theta=0.87376392 (0.87376392)
  <etotal_int>     -16.89110906 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.12728314 </eigenvalue_sum>
  Anderson extrapolation: theta=0.41341534 (0.41341534)
  <etotal_int>     -16.99255349 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.10566026 </eigenvalue_sum>
  Anderson extrapolation: theta=0.95404920 (0.95404920)
  <etotal_int>     -17.02284668 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.09878942 </eigenvalue_sum>
  Anderson extrapolation: theta=0.55510486 (0.55510486)
  <etotal_int>     -17.04426722 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.09246668 </eigenvalue_sum>
  Anderson extrapolation: theta=1.10281415 (1.10281415)
  <etotal_int>     -17.05377513 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.09003416 </eigenvalue_sum>
  Anderson extrapolation: theta=0.51761084 (0.51761084)
  <etotal_int>     -17.06113396 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.08502114 </eigenvalue_sum>
  Anderson extrapolation: theta=1.32113909 (1.32113909)
  <etotal_int>     -17.06430384 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.08195041 </eigenvalue_sum>
  Anderson extrapolation: theta=0.47626876 (0.47626876)
  <etotal_int>     -17.06696357 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.07817679 </eigenvalue_sum>
  Anderson extrapolation: theta=1.30656663 (1.30656663)
  <etotal_int>     -17.06799238 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.07390838 </eigenvalue_sum>
  Anderson extrapolation: theta=0.44226893 (0.44226893)
  <etotal_int>     -17.06874331 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.07023163 </eigenvalue_sum>
  Anderson extrapolation: theta=1.27964428 (1.27964428)
  <etotal_int>     -17.06909069 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.06537364 </eigenvalue_sum>
  Anderson extrapolation: theta=0.45927190 (0.45927190)
  <etotal_int>     -17.06942144 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.06252764 </eigenvalue_sum>
  Anderson extrapolation: theta=1.41180996 (1.41180996)
  <etotal_int>     -17.06967560 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05883123 </eigenvalue_sum>
  Anderson extrapolation: theta=0.53440221 (0.53440221)
  <etotal_int>     -17.07003338 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05700228 </eigenvalue_sum>
  Anderson extrapolation: theta=1.50726046 (1.50726046)
  <etotal_int>     -17.07030083 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05480674 </eigenvalue_sum>
  Anderson extrapolation: theta=0.59971434 (0.59971434)
  <etotal_int>     -17.07068451 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05379546 </eigenvalue_sum>
  Anderson extrapolation: theta=1.44877835 (1.44877835)
  <etotal_int>     -17.07093798 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05285421 </eigenvalue_sum>
  Anderson extrapolation: theta=0.61653045 (0.61653045)
  <etotal_int>     -17.07125071 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05248091 </eigenvalue_sum>
  Anderson extrapolation: theta=1.33058184 (1.33058184)
  <etotal_int>     -17.07142956 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05232803 </eigenvalue_sum>
  Anderson extrapolation: theta=0.58895947 (0.58895947)
  <etotal_int>     -17.07160674 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05228869 </eigenvalue_sum>
  Anderson extrapolation: theta=1.22435266 (1.22435266)
  <etotal_int>     -17.07169251 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05238350 </eigenvalue_sum>
  Anderson extrapolation: theta=0.55118570 (0.55118570)
  <etotal_int>     -17.07176099 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05240632 </eigenvalue_sum>
  Anderson extrapolation: theta=1.19695460 (1.19695460)
  <etotal_int>     -17.07179310 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05248637 </eigenvalue_sum>
  Anderson extrapolation: theta=0.53481414 (0.53481414)
  <etotal_int>     -17.07181865 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05250912 </eigenvalue_sum>
  Anderson extrapolation: theta=1.25235655 (1.25235655)
  <etotal_int>     -17.07183516 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05257116 </eigenvalue_sum>
  Anderson extrapolation: theta=0.55433376 (0.55433376)
  <etotal_int>     -17.07185330 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05260283 </eigenvalue_sum>
  Anderson extrapolation: theta=1.34584644 (1.34584644)
  <etotal_int>     -17.07186773 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05266592 </eigenvalue_sum>
  Anderson extrapolation: theta=0.59416935 (0.59416935)
  <etotal_int>     -17.07188655 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05269720 </eigenvalue_sum>
  Anderson extrapolation: theta=1.39019849 (1.39019849)
  <etotal_int>     -17.07190059 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05274430 </eigenvalue_sum>
  Anderson extrapolation: theta=0.62292711 (0.62292711)
  <etotal_int>     -17.07191860 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05275654 </eigenvalue_sum>
  Anderson extrapolation: theta=1.35784205 (1.35784205)
  <etotal_int>     -17.07193070 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05276587 </eigenvalue_sum>
  Anderson extrapolation: theta=0.62940106 (0.62940106)
  <etotal_int>     -17.07194473 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05275073 </eigenvalue_sum>
  Anderson extrapolation: theta=1.29931834 (1.29931834)
  <etotal_int>     -17.07195326 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05272335 </eigenvalue_sum>
  Anderson extrapolation: theta=0.62173508 (0.62173508)
  <etotal_int>     -17.07196198 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05269094 </eigenvalue_sum>
  Anderson extrapolation: theta=1.24861715 (1.24861715)
  <etotal_int>     -17.07196687 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05264864 </eigenvalue_sum>
  Anderson extrapolation: theta=0.60372805 (0.60372805)
  <etotal_int>     -17.07197130 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05261658 </eigenvalue_sum>
  Anderson extrapolation: theta=1.21163500 (1.21163500)
  <etotal_int>     -17.07197370 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05258080 </eigenvalue_sum>
  Anderson extrapolation: theta=0.58401474 (0.58401474)
  <etotal_int>     -17.07197575 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05255943 </eigenvalue_sum>
  Anderson extrapolation: theta=1.21147398 (1.21147398)
  <etotal_int>     -17.07197700 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05253791 </eigenvalue_sum>
  Anderson extrapolation: theta=0.57861531 (0.57861531)
  <etotal_int>     -17.07197823 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05252703 </eigenvalue_sum>
  Anderson extrapolation: theta=1.25935354 (1.25935354)
  <etotal_int>     -17.07197915 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05251650 </eigenvalue_sum>
  Anderson extrapolation: theta=0.59780676 (0.59780676)
  <etotal_int>     -17.07198026 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05251118 </eigenvalue_sum>
  Anderson extrapolation: theta=1.33031513 (1.33031513)
  <etotal_int>     -17.07198113 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05250536 </eigenvalue_sum>
  Anderson extrapolation: theta=0.63489179 (0.63489179)
  <etotal_int>     -17.07198224 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05250132 </eigenvalue_sum>
  Anderson extrapolation: theta=1.36655983 (1.36655983)
  <etotal_int>     -17.07198306 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05249577 </eigenvalue_sum>
  Anderson extrapolation: theta=0.66269505 (0.66269505)
  <etotal_int>     -17.07198406 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05249109 </eigenvalue_sum>
  Anderson extrapolation: theta=1.32575134 (1.32575134)
  <etotal_int>     -17.07198473 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05248478 </eigenvalue_sum>
  Anderson extrapolation: theta=0.65435113 (0.65435113)
  <etotal_int>     -17.07198543 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05248000 </eigenvalue_sum>
  Anderson extrapolation: theta=1.23536499 (1.23536499)
  <etotal_int>     -17.07198583 </etotal_int>
  total_electronic_charge: 8.00000000
  <eigenvalue_sum>  -2.05247460 </eigenvalue_sum>
  Anderson extrapolation: theta=0.61718561 (0.61718561)
  <etotal_int>     -17.07198618 </etotal_int>
  total_electronic_charge: 8.00000000
  <ekin>        12.38728117 </ekin>
  <econf>        0.00000000 </econf>
  <eps>        -20.24241225 </eps>
  <enl>          1.98631320 </enl>
  <ecoul>       -7.11063042 </ecoul>
  <exc>         -4.09253807 </exc>
  <esr>          1.47178349 </esr>
  <eself>       10.10653777 </eself>
  <ets>          0.00000000 </ets>
  <eexf>         0.00000000 </eexf>
  <etotal>     -17.07198637 </etotal>
  <epv>          0.00000000 </epv>
  <eefield>      0.00000000 </eefield>
  <enthalpy>   -17.07198637 </enthalpy>
<atomset>
<unit_cell 
    a=" 16.00000000   0.00000000   0.00000000"
    b="  0.00000000  16.00000000   0.00000000"
    c="  0.00000000   0.00000000  16.00000000" />
  <atom name="O" species="oxygen">
    <position> 0.00000000 0.00000000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> -0.01316231 -0.00000493 0.00000936 </force>
  </atom>
  <atom name="H1" species="hydrogen">
    <position> 1.12800000 1.44400000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00659212 0.00905256 -0.00004123 </force>
  </atom>
  <atom name="H2" species="hydrogen">
    <position> 1.12800000 -1.44400000 0.00000000 </position>
    <velocity> 0.00000000 0.00000000 0.00000000 </velocity>
    <force> 0.00654360 -0.00894733 -0.00002179 </force>
  </atom>
</atomset>
<unit_cell_a_norm> 16.000000 </unit_cell_a_norm>
<unit_cell_b_norm> 16.000000 </unit_cell_b_norm>
<unit_cell_c_norm> 16.000000 </unit_cell_c_norm>
<unit_cell_alpha>  90.000 </unit_cell_alpha>
<unit_cell_beta>   90.000 </unit_cell_beta>
<unit_cell_gamma>  90.000 </unit_cell_gamma>
<unit_cell_volume> 4096.000 </unit_cell_volume>
  <timing name="iteration" min="   12.784" max="   12.787"/>
</iteration>
<timing name="         charge" min="    4.029" max="    4.107"/>
<timing name="         energy" min="    3.987" max="    4.092"/>
<timing name="    ortho_align" min="    0.105" max="    0.142"/>
<timing name="      psda_prec" min="    0.028" max="    0.028"/>
<timing name="  psda_residual" min="    0.031" max="    0.057"/>
<timing name=" psda_update_wf" min="    0.029" max="    0.067"/>
<timing name="    update_vhxc" min="    4.302" max="    4.328"/>
<timing name="      wf_update" min="    0.291" max="    0.309"/>
<timing name="           ekin" min="    0.092" max="    0.207"/>
<timing name="            exc" min="    1.911" max="    2.029"/>
<timing name="           hpsi" min="    3.493" max="    3.523"/>
<timing name="       nonlocal" min="    0.361" max="    0.381"/>
<timing name=" charge_compute" min="    2.031" max="    2.182"/>
<timing name="charge_integral" min="    0.166" max="    0.326"/>
<timing name="  charge_rowsum" min="    0.122" max="    0.169"/>
<timing name="     charge_vft" min="    1.549" max="    1.639"/>
[qbox] <cmd>save test.xml</cmd>
 SampleWriter: write time: 0.072 s
 SampleWriter: file size: 3959423
 SampleWriter: aggregate write rate: 52.12 MB/s
[qbox]  End of command stream 
<real_time> 13.46 </real_time>
<end_time> 2016-04-06T12:24:32Z </end_time>
</fpmd:simulation>
