###
# Disable threshold based trigger for turning elastic indices read only due to low disc space

PUT http://localhost:9200/_cluster/settings HTTP/1.1
content-type: application/json

{
    "transient" : {
        "cluster.routing.allocation.disk.threshold_enabled" : false
    }
}

###
# Make calcs index writeable after accedental getting read only

PUT http://localhost:9200/calcs/_settings HTTP/1.1
content-type: application/json

{
    "index.blocks.read_only_allow_delete": null
}

###
# Delete unpublished calcs

POST http://localhost:19200/fairdi_nomad_migration/_delete_by_query HTTP/1.1
Content-Type: application/json

{
    "query": {
        "match": {
            "published": false
        }
    }
}


###
# Get errors from ELK
GET http://localhost:29200/logstash-2019.03.27/_search HTTP/1.1
content-type: application/json

{
    "size": 0,
    "query": {
        "match": {
            "level.keyword": "ERROR"
        }
    },
    "aggs": {
        "event": {
            "terms": {
                "field": "digest.keyword",
                "size": 100
            },
            "aggs": {
                "upload_path": {
                    "terms": {
                        "field": "nomad.migration.upload_path.keyword",
                        "size": 100
                    }
                }
            }
        }
    }
}

###
# Search migration unpublished calcs

GET http://localhost:19200/fairdi_nomad_mp/_search HTTP/1.1
Content-Type: application/json

{
    "size": 3,
    "query": {
        "bool": {
            "must": [
                { "match": { "code_name": "VASP" } }
            ]
        }
    },
    "aggs": {
        "upload_id": {
            "terms": {
                "field": "n_calculations"
            }
        }
    }
}

###
# Search

GET http://localhost:19200/fairdi_nomad_prod/_search HTTP/1.1
Content-Type: application/json

{
    "size": 1,
    "query": {
        "bool": {
            "must": [
                { "match": { "calc_hash": "CNyiqVrxIJbRhSgn4ADUy_wi_dBx" } }
            ]
        }
    },
    "aggs": {
        "upload_id": {
            "terms": {
                "field": "uploader.user_id"
            }
        }
    }
}

###
# Search test

GET http://localhost:9200/test_nomad_fairdi_0_6/_search HTTP/1.1
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must": [
              {
                "term": {
                  "published": true
                }
              },
              {
                "term": {
                  "with_embargo": false
                }
              }
            ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

###
# Disable refresh and replica for fast index
PUT http://localhost:19200/fairdi_nomad_prod/_settings HTTP/1.1
Content-Type: application/json

{
    "index" : {
        "number_of_replicas" : 0,
        "refresh_interval" : "-1"
    }
}

###
# Enable refresh and replica for fast index
PUT http://localhost:19200/fairdi_nomad_prod/_settings HTTP/1.1
Content-Type: application/json

{
    "index" : {
        "number_of_replicas" : 2,
        "refresh_interval" : null
    }
}

###
# Archive ES
GET http://localhost:19202/archive2018-09-24/_search HTTP/1.1
content-type: application/json

{
    "size": 1,
    "query": {
    },
    "aggs": {
        "codes": {
            "terms": {
                "field": "section_run.program_name"
            }
        }
    }
}

###
# Archive ES
GET http://localhost:19202/nomadarchiverepo/_search HTTP/1.1
content-type: application/json

{
    "size": 1,
    "query": {
    },
    "aggs": {
        "codes": {
            "terms": {
                "field": "program_name"
            }
        }
    }
}

###
#
GET http://localhost:19202/_reindex

###
# Reindex
POST http://localhost:19202/_reindex
content-type: application/json

{
  "source": {
    "remote": {
      "host": "http://nomad-flink-01.esc:9200"
    },
    "index": "fairdi_nomad_testing_major",
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "fairdi_nomad_testing_major"
  }
}

###
# Settings
PUT http://localhost:19202/_cluster/settings
content-type: application/json

{
    "transient" : {
        "reindex.remote.whitelist" : "localhost:9200"
    }
}
