###
# Disable threshold based trigger for turning elastic indices read only due to low disc space

PUT http://localhost:9200/_cluster/settings HTTP/1.1
content-type: application/json

{
    "transient" : {
        "cluster.routing.allocation.disk.threshold_enabled" : false
    }
}

###
# Make calcs index writeable after accedental getting read only

PUT http://localhost:9200/calcs/_settings HTTP/1.1
content-type: application/json

{
    "index.blocks.read_only_allow_delete": null
}

###
# Delete the calc index

DELETE http://localhost:9200/calcs HTTP/1.1


###

POST http://localhost:9200/calcs/_update_by_query HTTP/1.1
content-type: application/json

{
    "script": {
        "inline": "ctx._source.staging=false",
        "lang": "painless"
    },
    "query": {
        "match": {
            "upload_id": "epGwyPvaQ720_COyRvyLEg"
        }
    }
}

###
GET http://localhost:8000/nomad/api/admin/repair_uploads HTTP/1.1


###
GET http://localhost:8001/nomad/rawapi/raw/WUTlEULVrv6jEgFvSaOX1j0pF7on/examples_vasp/xml/Si.xml HTTP/1.1
Accept: application/json

###

curl -u other@gmail.com:nomad http://enc-staging-nomad.esc.rzg.mpg.de//nomad/api/uploads/CecjIXB1QeqJYzlim_qG8w HTTP/1.1

curl -u other@gmail.com:nomad http://enc-staging-nomad.esc.rzg.mpg.de//nomad/api/archive/0iyFlPv0JgHNXs1mZTzewly0tjzD/o6zkQdoHs1Cyy61Z-TmBo7PKmA0n HTTP/1.1
